# -*- coding: utf-8 -*-
"""Copy of Pandas Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-JWmPuD5HjvQIbHRBFNbKd1sxfcAa_9O

# **Pandas Practice 💪**

1- import pandas
"""

import pandas as pd

"""2- creat series like below"""

contry = pd.Series(["city","ingnis",800,"verna","venue","punto"])
print(contry)

companys=pd.Series(["Honda","maruti","Maruti","Hyundia","Hyundai", "Fiat"])
print(companys)

mony=pd.Series([900000, 600000, 100000, 800000, 950000, 750000])
print(mony)

data=pd.Series([5,7,10,4,2,6])
print(data)

df=pd.DataFrame({"car":contry,
                   "brand":companys,
                   "cost":mony,
                   "year":data})
(df)

"""3- creating Data Ftrame frome your series like below

4-select column
"""

print(companys)

"""5- select two columns"""

df[['car', 'cost']]

"""6- return dataframe to value"""

import numpy as np
p=np.array([df])
p

"""7- Selecting Elements use iloc or loc



"""

df.loc[0:1,["cost","year"]]

"""8- sort data by cost from high cost to low cost"""

df.sort_values(by=["cost"],ascending=False)

"""9- replace name of car 800 to toyota"""

df.at[2,"car"]="toyota"
df

"""10 - adding bool column has name "less 700" to know who is car cost less than 700000"""

a=df.cost>700000
df[ "less 700"]=a
df

"""11-drop year cloumn"""

del df['year']
df

"""12- insert new column has name "new year" after column "brand" """

import numpy as np
df.insert(3,"new year",[5.0,7.0,np.nan,7.0,5.0,np.nan])
df

"""13- using groupby to grouping year and use sum function to add cost for similarities """

df.groupby("year")['cost'].sum()